/// Excludes a mutable stored property from metadata generated by `@CodableEditor`.
///
/// Use this marker for any stored property that should not appear in the generated editor.
/// It also documents intentional immutable `let` properties and suppresses their macro warning.
@attached(peer)
public macro NotEditable() = #externalMacro(
    module: "SBJStructureMacros",
    type: "NotEditableMacro"
)
