import Foundation

/// A sendable reference to a bundle used by presentation resources.
///
/// Presentation-resource values should carry a stable description of where a resource lives,
/// rather than retaining a `Bundle` object. Besides making those descriptions safe to share
/// across concurrency domains, this keeps resource lookup at the rendering boundary.
///
/// `Bundle.module` is generated by SwiftPM only for a target that actually declares resources.
/// `#if SWIFT_PACKAGE` therefore is not sufficient to make a `.module` case compile safely.
/// When a target has SwiftPM resources and should expose `.module`, define
/// `SBJ_HAS_MODULE_BUNDLE` for that target. For example, in `Package.swift`:
///
/// ```swift
/// .target(
///     name: "SBJFoundation",
///     dependencies: ["SBJFoundationMacros"],
///     resources: [
///         .process("Resources"),
///     ],
///     swiftSettings: [
///         .define("SBJ_HAS_MODULE_BUNDLE"),
///         .enableUpcomingFeature("ApproachableConcurrency"),
///         .defaultIsolation(nil),
///     ]
/// )
/// ```
///
/// and add at least one resource beneath:
///
/// ```text
/// Sources/SBJFoundation/Resources/
/// ```
///
/// Do not define `SBJ_HAS_MODULE_BUNDLE` for a target without SwiftPM resources: in that case
/// SwiftPM does not synthesize `Bundle.module`.
public enum BundleReference: Sendable, Hashable {
    case main

    #if SBJ_HAS_MODULE_BUNDLE
    case module
    #endif

    case identifier(String)

    var bundle: Bundle? {
        switch self {
        case .main:
            return .main

        #if SBJ_HAS_MODULE_BUNDLE
        case .module:
            return .module
        #endif

        case .identifier(let identifier):
            return Bundle(identifier: identifier)
        }
    }
}
