import Foundation
import SwiftUI

/// A sendable reference to a bundle used by presentation resources.
///
/// Presentation-resource values should carry a stable description of where a resource lives,
/// rather than retaining a `Bundle` object. Besides making those descriptions safe to share
/// across concurrency domains, this keeps resource lookup at the rendering boundary.
///
/// `Bundle.module` is generated by SwiftPM only for a target that actually declares resources.
/// `#if SWIFT_PACKAGE` therefore is not sufficient to make a `.module` case compile safely.
/// When a target has SwiftPM resources and should expose `.module`, define
/// `SBJ_HAS_MODULE_BUNDLE` for that target. For example, in `Package.swift`:
///
/// ```swift
/// .target(
///     name: "SBJFoundation",
///     dependencies: ["SBJFoundationMacros"],
///     resources: [
///         .process("Resources"),
///     ],
///     swiftSettings: [
///         .define("SBJ_HAS_MODULE_BUNDLE"),
///         .enableUpcomingFeature("ApproachableConcurrency"),
///         .defaultIsolation(nil),
///     ]
/// )
/// ```
///
/// and add at least one resource beneath:
///
/// ```text
/// Sources/SBJFoundation/Resources/
/// ```
///
/// Do not define `SBJ_HAS_MODULE_BUNDLE` for a target without SwiftPM resources: in that case
/// SwiftPM does not synthesize `Bundle.module`.
public enum BundleReference: Sendable, Hashable {
    case main

    #if SBJ_HAS_MODULE_BUNDLE
    case module
    #endif

    case identifier(String)

    fileprivate var bundle: Bundle? {
        switch self {
        case .main:
            return .main

        #if SBJ_HAS_MODULE_BUNDLE
        case .module:
            return .module
        #endif

        case .identifier(let identifier):
            return Bundle(identifier: identifier)
        }
    }
}

/// A SwiftUI helper that distinguishes bundled image resources from SF Symbols.
///
/// `ImageName` is intentionally a SwiftUI-layer type. Use `ImageSource` when the
/// responsibility is loading image content rather than naming UI imagery.
///
/// LOCALIZATION / PRESENTATION NOTE: today these cases identify concrete image candidates.
/// Framework controls should still pass imagery through `ImageName` rather than constructing
/// `Image(systemName:)` directly. That gives the shared presentation-resource design one
/// boundary at which locale, culture, vendor, writing direction, accessibility, or theme may
/// later choose a different candidate. See Documents/LOCALIZATION_AND_PRESENTATION_RESOURCES.md.
public enum ImageName: Sendable, Hashable {
    case none
    case bundled(String, bundle: BundleReference = .main)
    case system(String)

    public var isEmpty: Bool {
        switch self {
        case .none:
            true
        case .bundled(let name, _):
            name.isEmpty
        case .system(let name):
            name.isEmpty
        }
    }
}

public extension Image {
    init(_ name: ImageName) {
        switch name {
        case .none:
            self = Image("")
        case .bundled(let name, let bundle):
            self = Image(name, bundle: bundle.bundle)
        case .system(let name):
            self = Image(systemName: name)
        }
    }
}

public extension Label where Title == Text, Icon == Image {
    init(_ title: LocalizedStringKey, image: ImageName) {
        switch image {
        case .none:
            self = Label {
                Text(title)
            } icon: {
                Image("")
            }
        case .bundled(let name, let bundle):
            self = Label {
                Text(title)
            } icon: {
                Image(name, bundle: bundle.bundle)
                    .renderingMode(.template)
            }
        case .system(let name):
            self = Label {
                Text(title)
            } icon: {
                Image(systemName: name)
            }
        }
    }

    init(_ title: String, image: ImageName) {
        switch image {
        case .none:
            self = Label(title, image: "")
        case .bundled(let name, let bundle):
            self = Label {
                Text(title)
            } icon: {
                Image(name, bundle: bundle.bundle)
                    .renderingMode(.template)
            }
        case .system(let name):
            self = Label(title, systemImage: name)
        }
    }
}
